### ISSUE TITLE
After installing cytoolz i get this error when i try to run brownie :-AttributeError:-partially initialized module 'cytoolz' has no attribute 'update_signature_registry' .

### ISSUE THREAD

**Issue by giridhar7889** [pytoolz/cytoolz#154]
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\brownie.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\brownie\__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "C:\Python310\lib\site-packages\brownie\project\__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "C:\Python310\lib\site-packages\brownie\project\main.py", line 36, in <module>
    from brownie.exceptions import (
  File "C:\Python310\lib\site-packages\brownie\exceptions.py", line 6, in <module>
    import eth_abi
  File "C:\Users\girid\AppData\Roaming\Python\Python310\site-packages\eth_abi\__init__.py", line 3, in <module>
    from eth_abi.abi import (  # NOQA
  File "C:\Users\girid\AppData\Roaming\Python\Python310\site-packages\eth_abi\abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "C:\Users\girid\AppData\Roaming\Python\Python310\site-packages\eth_abi\codec.py", line 11, in <module>
    from eth_utils import (
  File "C:\Python310\lib\site-packages\eth_utils\__init__.py", line 25, in <module>
    from .applicators import (  # noqa: F401
  File "C:\Python310\lib\site-packages\eth_utils\applicators.py", line 5, in <module>
    from .functional import to_dict
  File "C:\Python310\lib\site-packages\eth_utils\functional.py", line 17, in <module>
    from .toolz import compose as _compose
  File "C:\Python310\lib\site-packages\eth_utils\toolz.py", line 2, in <module>
    from cytoolz import (
  File "C:\Users\girid\AppData\Roaming\Python\Python310\site-packages\cytoolz-0.11.0-py3.10-win-amd64.egg\cytoolz\__init__.py", line 24, in <module>
    functoolz._sigs.update_signature_registry()
AttributeError: partially initialized module 'cytoolz' has no attribute 'update_signature_registry' (most likely due to a circular import)

**Comment by eriknw** [comment]
Interesting.  What version of `toolz`, `cytoolz`, and Python is this for?  Also, what version of Cython (if installed)?

**Comment by giridhar7889** [comment]
![ww](https://user-images.githubusercontent.com/62104626/142464234-755a72f2-a1dc-4432-9afa-5d4e0e9993dd.PNG)
Python version -3.10.0

**Comment by eriknw** [comment]
Thanks @giridhar7889.  I can reproduce this error with those versions.  Python 3.10 requires CyToolz 0.11.2.  Can you try upgrading `cytoolz` to version 0.11.2?

**Comment by giridhar7889** [comment]
Yeah i did upgraded to 0.11.2 but brownie requires cytoolz--0.11.0 version and it's showing me a dependency conflict has occurred .
![eee](https://user-images.githubusercontent.com/62104626/142469090-86c0c2d9-a8db-4f49-9428-7a2fab215960.PNG)

**Comment by giridhar7889** [comment]
Ohh yeah @eriknw now I can use brownie after upgrading my cytoolz package to 0.11.2.As of now, the brownie does recognize cytoolz 0.11.2.Thanks a lot man!!!.

**Comment by eriknw** [comment]
Cool, this was resolved by upgrading.  Thanks for reporting the issue @giridhar7889
